### ISSUE TITLE
Bells always generate with a wall on top of them

### ISSUE THREAD

**Issue by NixityNull** [mactso/Regrowth#16]
for some reason, every time i use this mod, the bells in villages seem to have the block above them myteriously replaced with walls. I don't know if this is the villagers' doing or simply a glitch in generation, but it has to be caused by this mod

**Comment by mactso** [comment]
It is.  

While the wall is present, the villagers will slowly build a town wall.
If the players remove that wall block, the villagers will not build a town wall.

It is intentional.  It is only created If wall building is turned on and only for the first 60 seconds the chunk exists.  After that it will not be replaced.

It allows players control over wall building.  It shouldn't be created if wall building is turned off at the server level.

Have a new release coming out soon for 1.17.1.  Also 1.16.5 and 1.17.1 will allow the server owner to have town clerics occasionally heal wounded villagers and badly wounded players.
