### ISSUE TITLE
A tree grew over my pigs

### ISSUE THREAD

**Issue by hacheraw** [mactso/Regrowth#41]
This is kinda funny kinda sad and I don't want to waste your time but I was starting a new game and bringing some animals near my place.

Before I decide where to make my corral I use to dig a 2x1 hole and place animals there. I had two holes, one with cows and one with pigs.
Next time I went to pet them I found that a tree grew in one of the holes 😆

![image](https://user-images.githubusercontent.com/10481749/209446122-7db16fd6-9ab8-42f8-a6c9-43fb116c8eca.png)

**Comment by mactso** [comment]
Hi, thanks for your interest in Regrowth.

Yes, pigs plant saplings by default in regrowth helping forests regrow (because that's what pigs do in real life sometimes too by digging in the ground with their snouts bringing up seeds close enough to germinate).

You can stop this in 3 ways.
1) Use a shovel to tamp down the grass floor of the pig pen to dirt_path.
2) Edit the configuration and remove the "pig" entry.
3) Put some other non growing block at the bottom of the hole
And I think this will work too.
4) Plant a tree next to the pigpen.  The saplings should not plant within 5 blocks of an existing tree.
5) Make the hole larger than 2x2 to 2x3 and the pigs will be shoved out of the way of the tree instead of being killed (and then won't plant another one).
With Best Regards,
Two Guys,
MacTso
